let
    Source = Web.BrowserContents("https://en.wikipedia.org/wiki/COVID-19_pandemic_by_country_and_territory"),
    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD[colspan=""5""]:not([rowspan]):nth-child(1):nth-last-child(1)"}, {"Column2", "DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD[colspan=""5""]:not([rowspan]):nth-child(1):nth-last-child(1)"}, {"Column3", "DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD[colspan=""5""]:not([rowspan]):nth-child(1):nth-last-child(1)"}, {"Column4", "DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD[colspan=""5""]:not([rowspan]):nth-child(1):nth-last-child(1)"}, {"Column5", "DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(1), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(1), DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR > TD[colspan=""5""]:not([rowspan]):nth-child(1):nth-last-child(1)"}}, [RowSelector="DIV.sticky-table-collapsible.mw-collapsible:nth-child(42) > DIV.sticky-table-scroll > TABLE.wikitable.sortable.sort-under.mw-datatable.plainrowheaders.sticky-table-row1.sticky-table-col2 > * > TR"]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Extracted Table From Html", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", type text}, {"Country", type text}, {"Deaths / million", Int64.Type}, {"Deaths", Int64.Type}, {"Cases", Int64.Type}}),
    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type",8)
in
    #"Removed Bottom Rows"